config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :invoices

  resources :customers do 
  resources :invoices
  end
  root 'customers#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :lineitems, :dependent => :destroy
  has_many :payments, :dependent => :destroy
  belongs_to :customer
  
  accepts_nested_attributes_for :lineitems, :allow_destroy => true
  accepts_nested_attributes_for :payments, :allow_destroy => true
  
  validates :invoice_no,
            presence: true,
            uniqueness: true
  
  after_touch :calculate_total, :calculate_remain, :calculate_payment
  after_initialize :generate_id
  
  def generate_id
    unless invoice_no
      last_invoice = Invoice.order(:invoice_no).last
      self.invoice_no = last_invoice ? last_invoice.invoice_no.succ : "IN001"
    end
  end

  def calculate_total
    self.total = lineitems.sum(:amount)
    self.save
  end

  def calculate_payment
    self.pay_total = payments.sum(:pay_amount)
    self.save
  end

  def calculate_remain
    self.pay_remain = self.total - payments.sum(:pay_amount)
    self.save
  end

end
 

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  def index
    @customer = current_user.customers.where(id: params[:customer_id]).first
    @invoices = if @customer.present?
    @customer.invoices
    else
      current_user.invoices
    end 
  end
  
  def show
    @customer = current_user.customers.where(id: params[:customer_id]).first
    @invoice = @customer.invoices.where(id: params[:id]).first
  end
  
  def new
    @customer = current_user.customers.where(id: params[:customer_id]).first
    @invoice = @customer.invoices.build
    # @invoice = Invoice.new 
  end
  
  def create
  @customer = current_user.customers.where(id: params[:customer_id]).first
  @invoice = @customer.invoices.build(invoice_params)
    if @invoice.save
      redirect_to customer_path(@customer)
    else
      render :new
    end
  end

   def update
    @customer = current_user.customers.where(id: params[:customer_id]).first
    @invoice = @customer.invoices.where(id: params[:id]).first
    if @invoice.update_attributes(invoice_params)

      redirect_to customer_path(@customer)
    end
  end
  
  def destroy
    @customer = current_user.customers.where(id: params[:customer_id]).first
    @invoice = @customer.invoices.where(id: params[:id]).first
    @invoice.destroy

    redirect_to :back
  end
  
  def edit
    @customer = current_user.customers.where(id: params[:customer_id]).first
    @invoice = @customer.invoices.where(id: params[:id]).first
  end
  
 

  def invoice_params
    params.require(:invoice).permit(:invoice_no, :total, :issue_date, :due_date, :customer_id, :pay_remain, :pay_total,
                                    lineitems_attributes: [:invoice_id, :id, :product_id, :product_name, :quantity, :unit_price, :amount, :_destroy],
                                    payments_attributes: [:invoice_id, :id, :pay_date, :pay_desc, :pay_method, :pay_amount, :_destroy])
  end
 
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/views/invoices/edit.html.erb
<div class="container">
  <%= nested_form_for [@customer,@invoice] do |f| %>
    <div class="row">
        <div class="col-xs-12">
        <div class="invoice-title">
        <div style="margin : auto; text-align: center">
          <%= image_tag attachment_url(current_user, :profile_image, :fill, 100, 100, format: "jpg") %>
  <h3 class="pull-right">Edit Invoice <%= @invoice.invoice_no %></h3>  </div>
       </div>
        <hr>
        <div class="row">
          <div class="col-xs-6">
            <address>
            <h4>Billed To:</h4><br>
              <%= current_user.first_name %> <%= current_user.last_name %><br>
              <%= @current_user.address %><br>
              <%= current_user.phone %><br>
              <%= current_user.email %>
            </address>
          </div>
          <div class="col-xs-6 text-right">
            <address>
              <h4>Shipped To:</h4><br>
              <%= @customer.customer_name %><br>
              <%= @customer.customer_address %><br>
              <%= @customer.phone_no %><br>
              <%= @customer.email %>
            </address>
          </div>
        </div>
        <div class="row">
          <div class="pull-right">
            <address>
              <strong>Order Date:</strong>
              <%= f.text_field :issue_date, data: { provide: 'datepicker' } %><br><br>
              <strong>Due Date:</strong>
              <%= f.text_field :due_date, data: { provide: 'datepicker' } %><br><br>
            </address>
          </div>
      </div>
    </div>

  <div class="container">
    <h3>Line Item</h3>
      <div class="row clearfix">
        <div class="col-md-12 column">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th class="text-center">
                  Product ID
                </th>
                <th class="text-center">
                  Product Name
                </th>
                <th class="text-center">
                  Unit Price
                </th>
                <th class="text-center">
                  Quantity
                </th>
              </tr>
            </thead>
            <tbody id="lineitems">
              <%= f.fields_for :lineitems, wrapper: false do |item| %>
              <tr class='fields'>
                <td>
                  <%= item.text_field :product_id, placeholder: "Product ID", class: "form-control" %>
                </td>
                <td>
                  <%= item.text_field :product_name, placeholder: "Product Name", class: "form-control" %>
                </td>
                <td>
                  <%= item.text_field :unit_price, placeholder: "Unit Price", class: "form-control" %>
                </td>
                <td>
                  <%= item.text_field :quantity, placeholder: "Quantity", class: "form-control" %>
                </td>
                <td>
                  <%= item.link_to_remove "Remove" %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= f.link_to_add 'Add Row', :lineitems, data: { target: '#lineitems' }, class: "btn btn-primary pull-right" %>
        </div>
      </div>
    </div>

      <div class="container">
    <h3>Payment</h3>
      <div class="row clearfix">
        <div class="col-md-12 column">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th class="text-center">
                  Payment Date
                </th>
                <th class="text-center">
                  Description
                </th>
                <th class="text-center">
                  Method
                </th>
                <th class="text-center">
                  Amount
                </th>
              </tr>
            </thead>
            <tbody id="payments">
              <%= f.fields_for :payments, wrapper: false do |item| %>
              <tr class='fields'>
                <td>
                  <%= item.text_field :pay_date,data: { provide: 'datepicker' }, placeholder: "Payment Date", class: "form-control" %>
                </td>
                <td>
                  <%= item.text_field :pay_desc, placeholder: "Description", class: "form-control" %>
                </td>
                <td>
                  <%= item.select :pay_method, [['Cash', 'Cash'], ['Cheque', 'Cheque'], ['Credit Card', 'Credit Card']], include_blank: 'Please select' %>
                </td>
                <td>
                  <%= item.text_field :pay_amount, placeholder: "Amount", class: "form-control" %>
                </td>
                <td>
                  <%= item.link_to_remove "Remove" %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= f.link_to_add 'Add Row', :payments, data: { target: '#payments' }, class: "btn btn-primary pull-right" %>
        </div>
      </div>
    </div>

  <%= f.submit "Save", class: "btn btn-default" %>
  <%= link_to 'Back', customer_path(@customer.id) %>
  <% end %>
</div>

app/views/invoices/index.html.erb
<div class="container">
  <h1>Invoice</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Invoice No</th>
        <th>Total</th>
        <th>Issue Date</th>
        <th>Due Date</th>
      </tr>
    </thead>
    <tbody>
      <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_no%></td>
        <td><%= invoice.total %></td>
        <td><%= invoice.issue_date %></td>
        <td><%= invoice.due_date %></td>
        <td>
          <%= link_to 'Show', invoice_path(invoice.id), class: "btn btn-info" %>
          <%= link_to 'Edit', edit_invoice_path(invoice.id), class: "btn btn-default" %>
          <%= link_to "Destroy",invoice, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New invoice', new_customer_invoice_path, class: "btn btn-primary", "data-no-turbolink" => true %>
</div>

app/views/invoices/new.html.erb
<div class="container">
  <h3><%= @customer.customer_name %></h3>
  <dl class="dl-horizontal">
    <dt>Name : </dt>
    <dd><%= @customer.customer_name %></dd>
    <dt>Address : </dt>
    <dd><%= @customer.customer_address %></dd>
    <dt>Telephone : </dt>
    <dd><%= @customer.phone_no %></dd>
    <dt>E-mail : </dt>
    <dd><%= @customer.email %></dd>
  </dl>
 
  <%= nested_form_for [@customer, @invoice], class: "form-horizontal" do |f| %>
  <%= f.label :invoice_no,class: "col-sm-10 control-label"%>
  <div class="form-group">
    <div class="col-md-6">
      <%= f.text_field :invoice_no, readonly: true, class: "form-control", placeholder: "invoice_no" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :due_date,class: "col-sm-8 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :due_date, data: { provide: 'datepicker' } %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :issue_date,class: "col-sm-8 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :issue_date, data: { provide: 'datepicker' } %>
    </div>
  </div>
  
  <div class="row clearfix">
    <div class="col-md-12 column">
      <h3>Line Item</h3>
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th class="text-center">
              Product ID
            </th>
            <th class="text-center">
              Product Name
            </th>
            <th class="text-center">
              Unit Price
            </th>
            <th class="text-center">
              Quantity
            </th>
          </tr>
        </thead>
        <tbody id="lineitems">
          <%= f.fields_for :lineitems, f.object.lineitems.build, wrapper: false do |item| %>
          <tr class='fields'>
            <td>
              <%= item.text_field :product_id, placeholder: "Product ID", class: "form-control" %>
            </td>
            <td>
              <%= item.text_field :product_name, placeholder: "Product Name", class: "form-control" %>
            </td>
            <td>
              <%= item.text_field :unit_price, placeholder: "Unit Price", class: "form-control" %>
            </td>
            <td>
              <%= item.text_field :quantity, placeholder: "Quantity", class: "form-control" %>
            </td>
            <td>
              <%= item.link_to_remove "Remove" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= f.link_to_add 'Add Row', :lineitems, data: { target: '#lineitems' }, class: "btn btn-primary pull-right" %>
    </div>
  </div>
  
  <%= f.submit "Save", class: "btn btn-default" %>
  <%= link_to 'Back', customer_path(@customer.id) %>
<% end %>
</div>

app/views/invoices/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
        <div class="invoice-title">
          <div style="margin : auto; text-align: center">
          <%= image_tag attachment_url(current_user, :profile_image, :fill, 100, 100, format: "jpg") %>
  
        <h3 class="pull-right"><%= @invoice.invoice_no %></h3>  </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-xs-6">
            <address>
            <h4>Billed To:</h4><br>
              <%= current_user.first_name %> <%= current_user.last_name %><br>
              <%= @current_user.address %><br>
              <%= current_user.phone %><br>
              <%= current_user.email %>
            </address>
          </div>
          <div class="col-xs-6 text-right">
            <address>
              <h4>Shipped To:</h4><br>
              <%= @customer.customer_name %><br>
              <%= @customer.customer_address %><br>
              <%= @customer.phone_no %><br>
              <%= @customer.email %>
            </address>
          </div>
        </div>
        <div class="row">
  
          <div class="pull-right">
            <address>
              <strong>Order Date:</strong>
              <%= @invoice.issue_date %><br>
              <strong>Due Date:</strong>
              <%= @invoice.due_date %><br><br>
            </address>
          </div>
      </div>
    </div>
    
  <!--
  <p>Created: <i><%= time_ago_in_words(@invoice.created_at) %> ago</i></p>
  -->
  <h4>Line Item</h4>
  <table class="table table-hover">
    <tr>
      <th><h4>Product ID</h4></th>
      <th><h4>Name</h4></th>
      <th><h4>Price</h4></th>
      <th><h4>Quantity</h4></th>
      <th></th>
      <th></th>
      <th></th>
      
      <% @invoice.lineitems.each do |lineitem| %>
      <tr>
        <td><h5><%= lineitem.product_id %></h5></td>
        <td><h5><%= lineitem.product_name %></h5></td>
        <td><h5><%= lineitem.unit_price %></h5></td>
        <td><h5><%= lineitem.quantity %></h5></td>
        <td>
          <%= link_to 'Edit', edit_customer_invoice_path(@customer, @invoice), class: "btn btn-default"%>
        </td>
      </tr>
      <% end %>
      <tfoot>
      <tr>
        <td></td>
        <td></td>
        <td class="right"><h4>Total</h4></td>
        <td class="right"><h4><%= @invoice.total %> Baht</h4></td>
        <td class="center"></td>
      </tr>
      </tfoot>
    </table>

  <h4>Payment</h4>
  <table class="table table-hover">
    <tr>
      <th><h4>Payment Date</h4></th>
      <th><h4>Description</h4></th>
      <th><h4>Method</h4></th>
      <th><h4>Amount</h4></th>
      <th></th>
      <th></th>
      <th></th>
      
      <% @invoice.payments.each do |payment| %>
      <tr>
        <td><h5><%= payment.pay_date %></h5></td>
        <td><h5><%= payment.pay_desc %></h5></td>
        <td><h5><%= payment.pay_method %></h5></td>
        <td><h5><%= payment.pay_amount %></h5></td>
        <td>
          <%= link_to 'Edit', edit_customer_invoice_path(@customer, @invoice), class: "btn btn-default"%>
        </td>
      </tr>
      <% end %>
      <tfoot>
      <tr>
        <td></td>
        <td></td>
        <td class="right"><h4>Total</h4></td>
        <td class="right"><h4><%= @invoice.pay_total %> Baht</h4></td>
        <td class="center"></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td class="right"><h4>Remain</h4></td>
        <td class="right"><h4><%= @invoice.pay_remain %> Baht</h4></td>
        <td class="center"></td>
      </tr>
      </tfoot>
    </table>


  <%= link_to 'Back', customer_path(@customer.id) %>