config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :invoices

  resources :customers do 
  resources :invoices
  end
  root 'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  belongs_to :user
  has_many :invoices, dependent: :destroy
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
   before_action :authenticate_user!

  def index
    @customers = current_user.customers
  end
  
  def show
    # @customer = current_user.customers.where(id: params[:id])
    # @customer = Customer.find params[:id]
    @customer = current_user.customers.where(id: params[:id]).first 
    @invoices = @customer.invoices.where(id: params[:id]).first
  end
  
  def new
    @customer = current_user.customers.new 
  
  end
  
  def create
    @customer = current_user.customers.new(customer_params)
    if @customer.save
      redirect_to customer_path(@customer)
    else
      render :new
    end
  end

  def update
    @customer = current_user.customers.where(id: params[:id]).first
    # @customer = Customer.find params[:id]
    if @customer.update_attributes(customer_params)
      redirect_to customers_path
    end
  end
  
  def destroy
   @customer = current_user.customers.where(id: params[:id]).first
    # @customer = Customer.find params[:id]
    @customer.destroy

    redirect_to :back
  end
  
  def edit
    @customer = current_user.customers.where(id: params[:id]).first
    # @customer = Customer.find params[:id]
  end

  private

  def customer_params
    params.require(:customer).permit(:user_id, :customer_name, :customer_address, :phone_no, :email, :first_name, :last_name, :phone, :address)
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/edit.html.erb
<div class="container">
  <h1>Edit Customer <%= @customer.customer_name %></h1>
  <%= form_for @customer do |f| %>
  <p>
    Address: <%= f.text_field :customer_address %>
  </p>
  <p>
    Telephone: <%= f.text_field :phone_no %>
  </p>
  <p>
    E-mail: <%= f.text_field :email %>
  </p>
  <%= f.submit "Save", class: "btn btn-default" %>
  <%= link_to 'Back', :action => nil %>
  <% end %>
</div>

app/views/customers/index.html.erb
<div class="container">
  <h1>Customer</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Customer Name</th>
        <th>Address</th>
        <th>Phone No</th>
        <th>E-mail</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.customer_name %></td>
        <td><%= customer.customer_address %></td>
        <td><%= customer.phone_no %></td>
        <td><%= customer.email %></td>
        <td>
          <%= link_to 'Show', customer_path(customer.id), class: "btn btn-info" %>
          <%= link_to 'Edit', edit_customer_path(customer.id), class: "btn btn-default" %>
          <%= link_to "Destroy",customer, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New customer', new_customer_path, class: "btn btn-primary", "data-no-turbolink" => true %>
</div>

app/views/customers/new.html.erb
<div class="container">
  <h2>New Customer</h2>
  
  <%= form_for @customer, class: "form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :Name,class: "col-sm-10 control-label"%>
      <div class="col-md-6">
        <%= f.text_field :customer_name, class: "form-control", placeholder: "customer_name" %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :Address,class: "col-sm-10 control-label"%>
      <div class="col-md-6">
        <%= f.text_area :customer_address, class: "form-control", placeholder: "customer_address" %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :Telephone,class: "col-sm-10 control-label"%>
      <div class="col-md-6">
        <%= f.text_field :phone_no, class: "form-control", placeholder: "phone_no" %>
      </div>
  </div>
  <div class="form-group">
      <%= f.label :Email,class: "col-sm-10 control-label"%>
      <div class="col-md-6">
        <%= f.text_field :email, class: "form-control", placeholder: "email" %>
      </div>
  </div>
    <%= f.submit "Save", class: "btn btn-default" %>
  <%= link_to 'Back', :action => nil %>
  <% end %>
</div>

app/views/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="invoice-title">
        <div style="margin : auto; text-align: center">
          <%= image_tag attachment_url(current_user, :profile_image, :fill, 100, 100, format: "jpg") %>
          
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-xs-6">
          <address>
            <h4>Billed To:</h4><br>
            <%= current_user.first_name %> <%= current_user.last_name %><br>
            <%= @current_user.address %><br>
            <%= current_user.phone %><br>
            <%= current_user.email %>
          </address>
        </div>
        <div class="col-xs-6 text-right">
          <address>
            <h4>Shipped To:</h4><br>
            <%= @customer.customer_name %><br>
            <%= @customer.customer_address %><br>
            <%= @customer.phone_no %><br>
            <%= @customer.email %>
          </address>
        </div>
      </div>
      <div class="row">
      </div>
    </div>
    <div class="container">
      <h4>Invoices of <%= @customer.customer_name %> </h4>
      <table class="table table-hover">
        <tr>
          <th><h4>Invoice</h4></th>
          <th><h4>Issue date</h4></th>
          <th><h4>Due date</h4></th>
          <th><h4>Total</h4></th>
          <th></th>
          <th></th>
        </tr>
        <% @customer.invoices.each do |invoice| %>
        <tr >
          <td><%= invoice.invoice_no %></td>
          <td><%= invoice.issue_date %></td>
          <td><%= invoice.due_date %></td>
          <td><%= invoice.total %></td>
          <td>
            <div style="margin : auto; text-align: center">
            <%= link_to 'Show', customer_invoice_path(@customer,invoice), class: "btn btn-info" %>
            <%= link_to 'Edit', edit_customer_invoice_path(@customer, invoice), class: "btn btn-default" %>
            <%= link_to 'Delete', customer_invoice_path(@customer, invoice), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
             </div>
          </td>
          <td>
          <div style="margin : auto; text-align: center">
            <%= link_to 'Add payment', edit_customer_invoice_path(@customer, invoice), class: "btn btn-success" %>
          </div>
        </td>
        </tr>
        <tfoot>
        </tfoot>
        <% end %>
        
      </table>
      <%= link_to "Add new invoice", new_customer_invoice_path(@customer), class: "btn btn-primary" if @customer %>
    </div>
  </div>
  <%= link_to 'Back', :action => nil %>